### ISSUE TITLE
Uncaught exception in reader crashing application

### ISSUE THREAD

**Issue by jheander** [dudleycarr/nsqjs#303] opened 2019-12-13 08:59 UTC
Hi!

I have an issue where if the nsqd process goes down or the network has some problem, it will unconditionally crash my application if I have an open Reader at the time this happens.

What happens is that I'm listening to a certain topic and channel and as part of this process the reader will try to write some data over the `NSQDConnection`. The write method on `nsqdconnection.js:424` will defer the actual writing by deferring the _flush function. When the flush function is executed the connection is down so the `this.conn.write()` call on `nsqdconnection.js:434` throws `ERR_STREAM_WRITE_AFTER_END`. However, this is running a deferred context on the main event loop and cannot be caught, so it bubbles all the way up and kills my application.

Expected behaviour: 
Handle the error and trigger the 'error' event on the `Reader` instance.

Actual behaviour:
Exception bubbles through the stack and kills the application. Impossible to trace which Reader that caused the error and therefore difficult to try to recover.

**Comment by dudleycarr** [comment] 2019-12-13 17:15
Even though the write is called asynchronously, it should not throw an error since there's a listener for the error event on the connection. That listener gets attached as soon as the connection is created and remains there until it's cleaned up.

Can you share a program that reproduces this issue for you? Can you enable the nsqjs debugging to show the state of the library when it does crash?

**Comment by jheander** [comment] 2019-12-13 18:02
Thanks for a fast response! Since it seems to be a race condition of the
connection being closed and a write, it seems to happen maybe once every
1000 connections (in our case that is once around once every hour) so it is
hard to write a succinct test case that reproduces it. But I will enable
nsqjs debugging and get some logs from the problem.

Den fre 13 dec. 2019 18:18Dudley Carr <notifications@github.com> skrev:

**Comment by dudleycarr** [comment] 2019-12-13 18:23
I'm curious why there are so many connections per hour. What's the life cycle of a Reader in your application? Are they short lived? Also, any idea why the network fails as often as once an hour?

**Comment by nekufa** [comment] 2020-02-27 15:19
@jheander did you solve the issue? maybe there is a workaround?

we have the same issue from time to time :(

```
events.js:298
      throw er; // Unhandled 'error' event
      ^
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:271:14)
    at Socket.Writable.write (_stream_writable.js:320:5)
    at NSQDConnection._flush (/app/node_modules/nsqjs/lib/nsqdconnection.js:434:19)
    at Immediate._onImmediate (/app/node_modules/nsqjs/lib/nsqdconnection.js:424:29)
    at processImmediate (internal/timers.js:456:21)
Emitted 'error' event on Reader instance at:
    at NSQDConnection.<anonymous> (/app/node_modules/nsqjs/lib/reader.js:234:12)
    at NSQDConnection.emit (events.js:321:20)
    at Socket.<anonymous> (/app/node_modules/nsqjs/lib/nsqdconnection.js:192:12)
    at Socket.emit (events.js:321:20)
    at errorOrDestroy (internal/streams/destroy.js:128:12)
    at writeAfterEnd (_stream_writable.js:273:3)
    at Socket.Writable.write (_stream_writable.js:320:5)
    at NSQDConnection._flush (/app/node_modules/nsqjs/lib/nsqdconnection.js:434:19)
    at Immediate.<anonymous> (/app/node_modules/nsqjs/lib/nsqdconnection.js:424:29)
```

**Comment by dudleycarr** [comment] 2020-02-27 23:23
@nekufa How often does this happen for you? Any idea if there's some kind of connectivity event or if the client initiated closing the connection? 

One thing that would be super helpful would be to put a couple of debug lines around the connection write. If you could put a try/catch around connection write and then print out connection destroyed status as well as what is in the buffer to be sent to NSQ. That would be helpful to diagnose the state of the connection at the time of throwing the exception.

**Comment by jheander** [comment] 2020-02-28 09:08
@nekufa We changed our application logic to only use a single long-lived Reader instance and filtering and distributing the messages in application logic. Since then we have not seen this error in production. I am pretty confident though that there is a bug or race condition here somewhere since when we had a short Reader life cycle this crash happened a couple of times per day and I mostly think that now the Reader turnover is so low that combined with the low frequency of this error it might take months or years before it happens again.

**Comment by nekufa** [comment] 2020-02-28 12:49
@dudleycarr we have an api gateway based on nodejs that accepts jsonrpc requests from backend services and forward messages to clients via socketio. so every gateway is a writer and every connected client is a reader. when socketio socket is connected we create a reader for that and when it is disconnecting we destroy reader. looks like an exception happens when reader is disconnected but nsqd sends a message to closed reader instance.

we've try some workaround like pause reader before closed, delayed close, but that did not help. in addition, we drop topic via nsqlookupd http api (/topic/delete?topic=name), i have no idea how to reproduce that. this happens once per 1-6 hours.. i can add any try catch, but looks like exception is thrown in a background process and i don't know where it can be placed. maybe you have any ideas what information can be helpful?

@jheander thanks! looks like applicable in our case, i will follow your way if solution will not be found

**Comment by jheander** [comment] 2020-02-28 13:08
@nekufa Your use-case is almost identical to ours and we structured our first solution in the same way and had approximately the same frequency of failures. The strange thing isn't really that the connection is closed, since that can happen due to clients dropping out, but that the exception is not caught and instead allowed to bubble all the way to the top and kill the application.

And even if we managed to catch it on application level, the context would be lost and we were unable to determine which connection that caused the problem and should be retried.

**Comment by vcealicu** [comment] 2020-03-30 21:14
I can confirm getting the same error. Use case: #ephemeral connections that close 5 seconds after the last client interested in the topic leaves. 

Error:
throw er; // Unhandled 'error' event
      ^

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:451:14)
    at NSQDConnection._flush (/home/vcealicu/node_modules/nsqjs/lib/nsqdconnection.js:434:19)
    at Immediate.<anonymous> (/home/vcealicu/node_modules/nsqjs/lib/nsqdconnection.js:424:29)
    at processImmediate (internal/timers.js:456:21)
Emitted 'error' event on Reader instance at:
    at NSQDConnection.<anonymous> (/home/vcealicu/node_modules/nsqjs/lib/reader.js:234:12)
    at NSQDConnection.emit (events.js:311:20)
    at Socket.<anonymous> (/home/vcealicu/node_modules/nsqjs/lib/nsqdconnection.js:192:12)
    at Socket.emit (events.js:311:20)
    at emitErrorNT (net.js:1336:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at processImmediate (internal/timers.js:429:9) {
  code: 'EPIPE'
}

I'll debug a bit more and open a pull request if when I figure out what is happening. It seems to occur mostly under heavy load.

**Comment by vcealicu** [comment] 2020-06-18 09:44
I'm getting it as well. Basically opening ephemeral connections on topics the users are interested in and then closing them when we have no more users listening to the topic. https://blog.cryptocompare.com/how-to-scale-order-book-integration-for-over-200-crypto-exchanges-313f30cf5ac2. 

It seems to be related to high load on the nsqd server.  I'll investigate a bit more on our side. Similar to what other people have been saying, very infrequent might be due to sending a msg.finish(); after the connection has dropped/is closed. 

```
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:266:14)
    at Socket.Writable.write (_stream_writable.js:315:5)
    at NSQDConnection._flush (/home/vcealicu/node_modules/nsqjs/lib/nsqdconnection.js:434:19)
    at Immediate._onImmediate (/home/vcealicu/node_modules/nsqjs/lib/nsqdconnection.js:424:29)
    at processImmediate (internal/timers.js:456:21)
Emitted 'error' event on Reader instance at:
    at NSQDConnection.<anonymous> (/home/vcealicu/node_modules/nsqjs/lib/reader.js:234:12)
    at NSQDConnection.emit (events.js:315:20)
    at Socket.<anonymous> (/home/vcealicu/node_modules/nsqjs/lib/nsqdconnection.js:192:12)
    at Socket.emit (events.js:315:20)
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at writeAfterEnd (_stream_writable.js:268:3)
    at Socket.Writable.write (_stream_writable.js:315:5)
    at NSQDConnection._flush (/home/vcealicu/node_modules/nsqjs/lib/nsqdconnection.js:434:19)
    at Immediate.<anonymous> (/home/vcealicu/node_modules/nsqjs/lib/nsqdconnection.js:424:29)
    at processImmediate (internal/timers.js:456:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
```

**Comment by dudleycarr** [comment] 2020-06-18 14:46
You said "and then closing them when we" -- what is "them" referring to being closed? Are you deleting the topic explicitly or are you deleting the topic by closing all of the Readers?

**Comment by vcealicu** [comment] 2020-06-18 20:16
closing the reader: 

`subscriptions[currentSub].nsq.reader.close();`

then catching the close message

```
subscriptions[currentSub].nsq.reader.on('nsqd_closed', function() {
        messageTypeInfo[subscriptionInfo.type].closed++;
        if (subscriptions[currentSub].is_ready === false) {
            common.LOG.toConsole('connectToNSQAndStartReceivingMessages: nsqd_closed ' + keyForNsq + ' before we got a ready message', common.LOG.WARNING, scriptParams.logLevel);
        }
        if (subscriptions[currentSub].mark_for_closing === true) {
            clearQueueDeleteNSQAndSub(currentSub);
            return;
        }
        common.LOG.toConsole('connectToNSQAndStartReceivingMessages: nsqd_closed ' + keyForNsq + ' unexpectedly', common.LOG.ERROR, scriptParams.logLevel);
        //do we have queue of clients waiting to be informed of this?
        let currentTimestamp = common.UTIL.getCurrentTimestamp();
        const forcedUnsubscribe = { 'TYPE': common.TYPE.FORCEDUNSUBSCRIBE, 'SUB': currentSub, 'INFO': 'Please reconnect on this subscription' };
        sendMessageToAllSubbedClients(currentSub, forcedUnsubscribe, function() {
            for (let socketId in subscriptions[currentSub].clients) {
                deleteSubFromTracking(subscriptions[currentSub].clients[socketId], socketId, currentSub, currentTimestamp);
            }
            clearQueueDeleteNSQAndSub(currentSub);
        });
    });
```

And cleaning up:

```
function clearQueueDeleteNSQAndSub(currentSub) {
    asyncNode.whilst(
        function() { return subscriptions[currentSub].callbacks_waiting_for_load.length > 0 },
        function(callbackIterationDone) {
            let callbackInQueue = subscriptions[currentSub].callbacks_waiting_for_load.shift();
            callbackInQueue(true);
            asyncNode.setImmediate(callbackIterationDone);
        },
        function(err) {
            if (err) {}
            common.LOG.toConsole('clearQueueDeleteNSQAndSub: Removing ' + currentSub + ' listeners', common.LOG.WARNING, scriptParams.logLevel);
            subscriptions[currentSub].nsq.reader.removeAllListeners('nsqd_connected');
            subscriptions[currentSub].nsq.reader.removeAllListeners('message');
            subscriptions[currentSub].nsq.reader.removeAllListeners('error');
            subscriptions[currentSub].nsq.reader.removeAllListeners('connection_error');
            subscriptions[currentSub].nsq.reader.removeAllListeners('nsqd_closed');
            delete subscriptions[currentSub].nsq;
            delete subscriptions[currentSub];
        }
    );
}
```

**Comment by dudleycarr** [comment] 2020-07-22 02:42
I believe the issue stems from buffering outgoing message even though they're being dispatched with setImmediate. It would be helpful if you could try a branch with the fix. Let me know if you're open to trying that. Sorry about the delayed reply?

**Comment by vcealicu** [comment] 2020-08-04 09:37
Hello @dudleycarr, sorry for the later reply, and thanks for looking into this. I'm more than happy to try a branch with the fix. I have not seen it happen in a very long time, might have been because we were running multiple instances with the same topic and we've switched some of the infrastructures around for other reasons. Let me know which branch and I'll give it a go on our staging environment.

**Closed** 2021-06-06 05:25 UTC
